apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      name: {appName}
      labels:
        app: {appName}
    spec:
      containers:
      - name: {appName}
        image: {image}
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
